# Generated by Django 5.2.6 on 2025-09-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pointsledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
