# Generated by Django 5.2.6 on 2025-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_drivernotificationpreference_sound_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernotificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drivernotificationpreference',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
