# Generated by Django 5.2.6 on 2025-09-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_length", models.PositiveIntegerField(default=12)),
                ("require_upper", models.BooleanField(default=True)),
                ("require_lower", models.BooleanField(default=True)),
                ("require_digit", models.BooleanField(default=True)),
                ("require_symbol", models.BooleanField(default=True)),
                (
                    "expiry_days",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = never expires"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Password policy",
                "verbose_name_plural": "Password policies",
            },
        ),
    ]
