# Generated by Django 5.2.6 on 2025-09-25 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordpolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.BooleanField(default=True)),
                ('points', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Notification Preference',
                'verbose_name_plural': 'Driver Notification Preferences',
            },
        ),
    ]
