# Generated by Django 5.2.6 on 2025-10-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_message_messagerecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
