# Generated by Django 5.2.6 on 2025-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_driverprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
