# Generated by Django 5.2.6 on 2025-10-09 15:10

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_driverprofile_sponsor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='image',
            field=models.ImageField(blank=True, default='media/defaults/avatar.png', upload_to=accounts.models.avatar_upload_path_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
