# Generated by Django 5.2.6 on 2025-10-09 15:49

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_driverprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=accounts.models.avatar_upload_path_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
