# Generated by Django 5.2.6 on 2025-10-14 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_driverprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernotificationpreference',
            name='sound_file',
            field=models.FileField(blank=True, null=True, upload_to='notif_sounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])]),
        ),
        migrations.AddField(
            model_name='drivernotificationpreference',
            name='sound_mode',
            field=models.CharField(choices=[('default', 'Default chime'), ('silent', 'Silent'), ('custom', 'Custom file')], default='default', max_length=20),
        ),
    ]
