# Generated by Django 5.2.7 on 2025-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='session_timeout_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Per-user inactivity timeout in seconds (blank = use system default)', null=True),
        ),
    ]
