# Generated by Django 5.2.6 on 2025-10-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_drivernotificationpreference_email_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernotificationpreference',
            name='theme',
            field=models.CharField(choices=[('system', 'System / Default'), ('light', 'Light'), ('dark', 'Dark'), ('contrast', 'High Contrast')], default='system', help_text='Visual theme preference.', max_length=20),
        ),
    ]
