# Generated by Django 5.2.6 on 2025-10-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_drivernotificationpreference_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernotificationpreference',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français')], default='en', max_length=10),
        ),
    ]
