# Generated by Django 5.2.7 on 2025-10-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_driverprofile_session_timeout_seconds'),
        ('accounts', '0015_drivernotificationpreference_language'),
    ]

    operations = [
    ]
