# Generated by Django 5.2.6 on 2025-10-27 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_failedloginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernotificationpreference',
            name='low_balance_threshold',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='DriverSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_balance_alert_enabled', models.BooleanField(default=True)),
                ('low_balance_threshold', models.PositiveIntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
