# Generated by Django 5.2.6 on 2025-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_drivernotificationpreference_low_balance_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernotificationpreference',
            name='low_balance_alert_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
