# Generated by Django 5.2.7 on 2025-10-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_drivernotificationpreference_low_balance_alert_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="If checked, this user is prevented from logging in (admin only)",
            ),
        ),
    ]
