# Generated by Django 5.2.7 on 2025-10-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_complaint"),
        ("accounts", "0019_driverprofile_is_locked"),
    ]

    operations = []
