# Generated by Django 5.2.7 on 2025-10-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_merge_0018_complaint_0019_driverprofile_is_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="If checked, this user is temporarily suspended and cannot access any part of the system (admin only)",
            ),
        ),
    ]
