# Generated by Django 5.2.6 on 2025-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_usermfa"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex color code for label display (e.g. #ff0000)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Custom Label",
                "verbose_name_plural": "Custom Labels",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Admin-assigned tags for categorizing users.",
                related_name="drivers",
                to="accounts.customlabel",
            ),
        ),
    ]
