# Generated by Django 5.2.7 on 2025-11-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_customlabel_driverprofile_labels"),
        ("accounts", "0024_securityquestion_usersecurityanswer"),
    ]

    operations = []
