# Generated by Django 5.2.7 on 2025-11-11 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_merge_20251104_1935'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, help_text="If checked, this sponsor is archived and won't appear in regular searches")),
                ('archived_at', models.DateTimeField(blank=True, help_text='When the sponsor was archived', null=True)),
                ('archived_by', models.ForeignKey(blank=True, help_text='Admin who archived this sponsor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_sponsors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
