# Generated by Django 5.2.7 on 2025-11-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_sponsorshiprequest"),
    ]

    operations = []
