# Generated by Django 5.2.7 on 2025-11-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_sponsorshiprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshiprequest",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sponsorshiprequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("driver_to_sponsor", "Driver → Sponsor"),
                    ("sponsor_to_driver", "Sponsor → Driver"),
                ],
                default="driver_to_sponsor",
                help_text="Indicates who initiated the request",
                max_length=20,
            ),
        ),
    ]
