# Generated by Django 5.2.7 on 2025-11-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_sponsorshiprequest_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshiprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("ended", "Ended"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
