# Generated by Django 5.2.7 on 2025-11-11 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_alter_sponsorshiprequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="sponsors",
            field=models.ManyToManyField(
                blank=True,
                related_name="sponsored_drivers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
