# Generated by Django 5.2.6 on 2025-11-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_sponsorapplication'),
        ('accounts', '0027_chatroom_chatmessage_messagereadstatus'),
        ('accounts', '0030_driverprofile_sponsors'),
    ]

    operations = [
    ]
