# Generated by Django 5.2.7 on 2025-11-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_merge_20251111_1217"),
        ("accounts", "0031_merge_20251111_1558"),
    ]

    operations = []
