# Generated by Django 5.2.6 on 2025-11-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_sponsorpointsaccount_sponsorpointstransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='points_goal',
            field=models.PositiveIntegerField(blank=True, help_text='Personal points goal for progress tracking', null=True),
        ),
    ]
