# Generated by Django 5.2.6 on 2025-11-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_add_points_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='points_per_usd',
            field=models.PositiveIntegerField(blank=True, help_text='Points per USD for this sponsor (if not set, uses global default)', null=True),
        ),
    ]
