# Generated by Django 5.2.6 on 2025-11-17 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_add_sponsor_fee_ratio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Name of the uploaded file', max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0, help_text='Total rows processed')),
                ('created_count', models.PositiveIntegerField(default=0, help_text='Users successfully created')),
                ('skipped_count', models.PositiveIntegerField(default=0, help_text='Rows skipped (duplicates, invalid data)')),
                ('error_count', models.PositiveIntegerField(default=0, help_text='Rows with errors')),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of error messages')),
                ('created_users', models.JSONField(blank=True, default=list, help_text='List of usernames created')),
                ('skipped_users', models.JSONField(blank=True, default=list, help_text='List of usernames skipped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(help_text='Admin who performed the upload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Upload Log',
                'verbose_name_plural': 'Bulk Upload Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
