# Generated by Django 5.2.7 on 2025-11-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_impersonation_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockoutPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_failed_attempts', models.PositiveIntegerField(default=5, help_text='Maximum number of failed login attempts before lockout')),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=30, help_text='How long (in minutes) the account remains locked after max attempts')),
                ('reset_attempts_after_minutes', models.PositiveIntegerField(default=60, help_text='Reset failed attempt counter after this many minutes of inactivity')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable account lockout policy')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lockout policy',
                'verbose_name_plural': 'Lockout policies',
            },
        ),
    ]
