# Generated by Django 5.2.7 on 2025-11-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_lockout_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsledger',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When these points expire (null = never expires)', null=True),
        ),
    ]

