# Generated by Django 5.2.6 on 2025-11-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_add_pointsledger_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='widget_order',
            field=models.JSONField(blank=True, default=list, help_text="Order of dashboard widgets (e.g., ['points', 'orders', 'wishlist'])"),
        ),
    ]
