# Generated by Django 5.2.6 on 2025-10-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_wishlist_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]