# Generated by Django 5.2.6 on 2025-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_wishlist_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_usd', models.PositiveIntegerField(default=100, help_text='How many points per $1')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Points Configuration',
                'verbose_name_plural': 'Points Configuration',
            },
        ),
    ]
