# Generated by Django 5.2.6 on 2025-11-17 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_increase_url_field_lengths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('points_cost', models.PositiveIntegerField(default=0, help_text='Points required to purchase')),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('product_url', models.URLField(blank=True, max_length=1000)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only active items are shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_catalog_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sponsor Catalog Item',
                'verbose_name_plural': 'Sponsor Catalog Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('points_cost', models.PositiveIntegerField(default=0, help_text='Points required to purchase')),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('product_url', models.URLField(blank=True, max_length=1000)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, default='New', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Only active items are shown to drivers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Sponsor/admin who added this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items_added', to=settings.AUTH_USER_MODEL)),
                ('source_sponsor_item', models.ForeignKey(blank=True, help_text='Original sponsor catalog item if this was added from sponsor catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_catalog_items', to='shop.sponsorcatalogitem')),
            ],
            options={
                'verbose_name': 'Driver Catalog Item',
                'verbose_name_plural': 'Driver Catalog Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
