# Generated by Django 5.2.6 on 2025-11-17 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_add_sponsor_and_driver_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Saved Cart', help_text='Name for this saved cart', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total points for all items in this saved cart')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Cart',
                'verbose_name_plural': 'Saved Carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=255)),
                ('points_each', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('saved_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.savedcart')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
    ]
