# Generated by Django 5.2.7 on 2025-11-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_add_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsconfig',
            name='points_expiry_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of days until points expire (0 = never expires)'),
        ),
    ]

